# Generated by Django 3.2.13 on 2022-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tempat_lahir',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tgl_lahir',
            field=models.DateField(null=True),
        ),
    ]
