# Generated by Django 3.2.13 on 2022-10-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jns_krywn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.jenis'),
        ),
    ]
