# Generated by Django 3.2.14 on 2022-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_user_kelas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
