# Generated by Django 3.2.14 on 2022-07-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_user_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kelas_id',
        ),
    ]
