# Generated by Django 3.2.14 on 2022-07-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_remove_user_kelas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kelas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.kelas'),
        ),
    ]
