# Generated by Django 3.2.15 on 2022-08-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doa', models.CharField(max_length=100)),
                ('ayat', models.CharField(max_length=100)),
                ('artinya', models.CharField(max_length=1000)),
            ],
        ),
    ]
