# Generated by Django 3.2.15 on 2022-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doa',
            name='latin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
