# Generated by Django 3.2.15 on 2022-08-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_kelas_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.kelas_siswa'),
        ),
    ]
