# Generated by Django 3.2.14 on 2022-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tgl_upload', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/book')),
                ('jumlah', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
