# Generated by Django 3.2.14 on 2022-08-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_book_jumlah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
