# Generated by Django 3.2.15 on 2022-08-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_kelompok_buku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book_pics/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Rak_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.rak_book')),
                ('kelompok_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.kelompok_buku')),
                ('no_registrasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.no_reg')),
                ('penerbit_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.penerbit')),
                ('penulis_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.penulis')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.tema')),
            ],
        ),
    ]
