# Generated by Django 3.2.13 on 2022-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=1000000)),
                ('article', models.CharField(max_length=100000000)),
                ('image', models.ImageField(upload_to='img_article/')),
                ('sub_image', models.ImageField(default='0', upload_to='img_article/sub_img_article/')),
                ('sub_image_2', models.ImageField(default='0', upload_to='img_article/sub_img_article/')),
                ('sub_image_3', models.ImageField(default='0', upload_to='img_article/sub_img_article/')),
                ('sub_image_4', models.ImageField(default='0', upload_to='img_article/sub_img_article/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
